Feat/todo edit
ruubyme/todo-list-typescript pull request #4
Opened 2023-03-20 23:32 UTC by ruubyme

상세페이지로 이동을 안함

2023-03-21 12:17 UTC, m1nsuppp requested changes
피드백 반영해주세요~!

2023-03-21 12:17 UTC, m1nsuppp commented on src/components/Todo.tsx
> +      <Link to={`/todos/${todo.id}`}>{todo.value}</Link>
라우팅하기 위한 `path`는 잘 정의하신 것 같습니다!

2023-03-21 12:17 UTC, m1nsuppp commented on src/components/TodoDetail.tsx
> +type Todo = {
여기도 마찬가지로 똑같은 코드를 또 작성하게 됐네요~
다음부터는 하나의 파일에서 `todo`에 대한 type을 정의하고 `export`하여 여러 파일에서 사용할 수 있도록 해보세요!

2023-03-21 12:17 UTC, m1nsuppp commented on src/components/TodoDetail.tsx
> +  useEffect(() => {
`useEffect`를 꼭 사용해야만 문제를 해결할 수 있었나요?
그렇다면 그 이유가 궁금합니다.

2023-03-21 12:17 UTC, m1nsuppp commented on src/components/Todo.tsx
> +      <Link to={`/todos/${todo.id}`}>{todo.value}</Link>
하지만 상세 페이지로 이동하지 않는 이유는 라우팅에 관한 설정을 안해주었기 때문입니다.

2023-03-21 12:17 UTC, m1nsuppp commented on src/main.tsx
> +  //<React.StrictMode>
`strict` 모드를 왜 끄셨나요?

2023-03-21 12:17 UTC, m1nsuppp commented on src/main.tsx
> +  //<React.StrictMode>
해당 파일에서 다음과 같은 설정이 필요합니다.

```typescript
import React from 'react'
import ReactDOM from 'react-dom/client'
import {
  createBrowserRouter,
  RouterProvider,
} from "react-router-dom";
import App from './App'
import './index.css'

const router = createBrowserRouter([
  {
    path: "/",
    element: <App />,
  },
  {
    path: '/todos/:id',
    element: <TodoDetail />
  }
]);

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>,
)

```

2023-03-21 12:17 UTC, m1nsuppp commented on src/main.tsx
> +  //<React.StrictMode>
자세한 내용은 [여기를 참고하세요~!](https://reactrouter.com/en/main/start/tutorial)

2023-03-22 13:00 UTC, ruubyme commented on src/components/TodoDetail.tsx
> +type Todo = {
중복되는 부분 수정완료했습니다 :)

2023-03-22 13:14 UTC, ruubyme commented on src/main.tsx
> +  //<React.StrictMode>
1. BrowserRouter는 최상위 컴포넌트에서 생성해야 된다고 이해했습니다(이 프로젝트의 경우 main.tsx)
2. 만약 1번 내용이 제대로 이해한게 맞다면 element: <TodoDetail /> 부분에서 TodoDetail 컴포넌트에 필요한 prop들을 내려주지 않아서 오류가 발생하는데 .. 바보같은 질문일 수 있지만 어떻게 main.tsx에서 prop을 내려줄 수 있을까요?

2023-03-22 13:24 UTC, m1nsuppp commented on src/main.tsx
> +  //<React.StrictMode>
> 1. BrowserRouter는 최상위 컴포넌트에서 생성해야 된다고 이해했습니다(이 프로젝트의 경우 main.tsx)
> 2. 만약 1번 내용이 제대로 이해한게 맞다면 element:  부분에서 TodoDetail 컴포넌트에 필요한 prop들을 내려주지 않아서 오류가 발생하는데 .. 바보같은 질문일 수 있지만 어떻게 main.tsx에서 prop을 내려줄 수 있을까요?
- 물론 가능은 하겠지만, 그렇게 한다면... 단점들이 많겠죠?
- 그렇다면 `/pages`라는 디렉토리를 만들어 상세 정보를 렌더링해주는 페이지를 만들어주면 좋겠죠?
- 이에 대해서는 **_react pages 폴더_** 또는 **_react pages 디렉토리_** 등으로 검색해보세요~!

2023-03-22 13:27 UTC, m1nsuppp commented on src/components/TodoDetail.tsx
> +type Todo = {
> 중복되는 부분 수정완료했습니다 :)

- 좋아요!👍👍 수정하신 내용이 있다면 커밋을 해주셔야 제가 확인할 수 있습니다!

2023-03-29 14:15 UTC, m1nsuppp approved these changes
LGTM👍

2023-03-29 14:15 UTC, m1nsuppp commented
고생많으셨어요~!!

2023-03-29 14:15 UTC, closed without merging